/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Catholomew (https://sketchfab.com/Catholomew)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/shinra-helicopter-crisis-core-63baf81581b749baa82def69241c14f4
Title: Shinra Helicopter - Crisis Core
*/

import { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import scene from "../assets/3d/helicopter.glb";

const Helicopter = ({ currentAnimation, filledInputs, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);
  const timeScaleValues = [0.05, 0.1, 0.2, 5];

  useEffect(() => {
    if (currentAnimation === "Idle") {
      actions[currentAnimation].play();
      actions[currentAnimation].timeScale = timeScaleValues[filledInputs];
    } else {
      actions["Idle"].stop();
    }
  }, [actions, currentAnimation, filledInputs]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          // rotation={[-Math.PI / 2, 0, 0]}
          // scale={1.631}
        >
          <group name="root">
            <group
              name="GLTF_SceneRootNode"
              //  rotation={[Math.PI / 2, 0, 0]}
            >
              <group
                name="b0_31"
                // position={[0, -0.24, -0.126]}
                // rotation={[1.7, 0, 1.9]}
                // scale={0.005}
              >
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.ffccdif_0}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <skinnedMesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.ffccdif_1}
                    skeleton={nodes.Object_9.skeleton}
                  />
                  <skinnedMesh
                    name="Object_11"
                    geometry={nodes.Object_11.geometry}
                    material={materials.ffccdif_0}
                    skeleton={nodes.Object_11.skeleton}
                  />
                  <skinnedMesh
                    name="Object_13"
                    geometry={nodes.Object_13.geometry}
                    material={materials.ffccdif_1}
                    skeleton={nodes.Object_13.skeleton}
                  />
                  <skinnedMesh
                    name="Object_15"
                    geometry={nodes.Object_15.geometry}
                    material={materials.ffccdif_0}
                    skeleton={nodes.Object_15.skeleton}
                  />
                  <skinnedMesh
                    name="Object_17"
                    geometry={nodes.Object_17.geometry}
                    material={materials.ffccdif_1}
                    skeleton={nodes.Object_17.skeleton}
                  />
                  <skinnedMesh
                    name="Object_19"
                    geometry={nodes.Object_19.geometry}
                    material={materials.ffccdif_0}
                    skeleton={nodes.Object_19.skeleton}
                  />
                  <group name="mesh0_24" />
                  <group name="mesh1_25" />
                  <group name="mesh2_26" />
                  <group name="mesh3_27" />
                  <group name="mesh4_28" />
                  <group name="mesh5_29" />
                  <group name="mesh6_30" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

export default Helicopter;
